### ISSUE TITLE
Outcome 5 Resolution

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/LDRS500#20]

**Comment by cmadland** [comment]
![image](https://user-images.githubusercontent.com/12282929/27311707-a90c2890-5517-11e7-845a-9e942bfe021d.png)

**Comment by smecastellon** [comment]
Yes this is the assignment I suggested to address outcome 5 - Imbenzi what
do you think?


*"Do Justice, love mercy and walk humbly with your God." *Micah 6:8

Adrienne Castellon, EdD

Asst. Prof. and Stream Director of Master's Educational Leadership
Asst. Prof. Master's Special Education
Asst. Prof. Faculty of Education

Trinity Western University
7600 Glover Road
Langley, BC V2Y 1Y1, Canada
email: adrienne.castellon@twu.ca
www.twu.ca/lead
http://www.twu.ca/leadership-ma/education

Current Research:
http://www.teacherresearch.ca/blog/article/2017/05/28/324-a-call-to-personal-research-indigenizing-your-curriculum

[image: cid:34908F1D-3E32-4B46-AD9B-17D22312D87D]

**Comment by Imbenzig** [comment]
I agree with Adrienne. It look good.

**Comment by smecastellon** [comment]
Thanks Imbenzi!


*"Do Justice, love mercy and walk humbly with your God." *Micah 6:8

Adrienne Castellon, EdD

Asst. Prof. and Stream Director of Master's Educational Leadership
Asst. Prof. Master's Special Education
Asst. Prof. Faculty of Education

Trinity Western University
7600 Glover Road
Langley, BC V2Y 1Y1, Canada
email: adrienne.castellon@twu.ca
www.twu.ca/lead
http://www.twu.ca/leadership-ma/education

Current Research:
http://www.teacherresearch.ca/blog/article/2017/05/28/324-a-call-to-personal-research-indigenizing-your-curriculum

[image: cid:34908F1D-3E32-4B46-AD9B-17D22312D87D]
