### ISSUE TITLE
Follow the Leader

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/LDRS500#28]
@smecastellon the Follow The Leader assignment asks students to follow someone on social media for 2 weeks prior to the beginning of the class, and then submit the report at the end of the first week.

How will students be informed before class starts that they need to follow someone?

Should we adjust this so that it can be completed in the first week? They can still identify a leader and dig into their SM profiles and posts to gather info.

**Comment by smecastellon** [comment]
Hi Colin
I normally email them two weeks prior and because they are doing prework it's part of that in face to face. Yes, please adjust so done in  first week - that'll work!
